# Generated by Django 4.2.30 on 2026-05-09 08:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jobs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SyncQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('checklist_update', 'Checklist Update'), ('status_change', 'Status Change'), ('photo_upload', 'Photo Upload'), ('signature_upload', 'Signature Upload')], max_length=20)),
                ('payload', models.JSONField()),
                ('retry_count', models.IntegerField(default=0)),
                ('last_retry', models.DateTimeField(blank=True, null=True)),
                ('next_retry', models.DateTimeField(blank=True, help_text='When to attempt retry (exponential backoff)', null=True)),
                ('completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_queue_items', to='jobs.job')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'sync_queue',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['completed', 'next_retry'], name='sync_queue_complet_3ec603_idx'), models.Index(fields=['job', 'action'], name='sync_queue_job_id_e0cead_idx')],
            },
        ),
        migrations.CreateModel(
            name='Conflict',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('local_data', models.JSONField()),
                ('server_data', models.JSONField()),
                ('conflicting_fields', models.JSONField(default=list)),
                ('resolved', models.BooleanField(default=False)),
                ('resolution', models.CharField(choices=[('keep_local', 'Keep Local Changes'), ('keep_server', 'Accept Server Version'), ('merged', 'Manually Merged')], max_length=20, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conflicts', to='jobs.job')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'conflicts',
                'indexes': [models.Index(fields=['job', 'resolved'], name='conflicts_job_id_a4e540_idx')],
            },
        ),
    ]
