// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

const String _androidApiKey =
    String.fromEnvironment('FIREBASE_ANDROID_API_KEY', defaultValue: '');
const String _androidAppId =
    String.fromEnvironment('FIREBASE_ANDROID_APP_ID', defaultValue: '');
const String _iosApiKey =
    String.fromEnvironment('FIREBASE_IOS_API_KEY', defaultValue: '');
const String _iosAppId =
    String.fromEnvironment('FIREBASE_IOS_APP_ID', defaultValue: '');
const String _messagingSenderId =
    String.fromEnvironment('FIREBASE_MESSAGING_SENDER_ID', defaultValue: '');
const String _projectId =
    String.fromEnvironment('FIREBASE_PROJECT_ID', defaultValue: '');
const String _storageBucket =
    String.fromEnvironment('FIREBASE_STORAGE_BUCKET', defaultValue: '');
const String _iosBundleId =
    String.fromEnvironment('FIREBASE_IOS_BUNDLE_ID', defaultValue: '');

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Provide values through Flutter build/run defines:
///
/// ```bash
/// flutter run --dart-define=FIREBASE_ANDROID_API_KEY=... \
///   --dart-define=FIREBASE_ANDROID_APP_ID=... \
///   --dart-define=FIREBASE_IOS_API_KEY=... \
///   --dart-define=FIREBASE_IOS_APP_ID=... \
///   --dart-define=FIREBASE_MESSAGING_SENDER_ID=... \
///   --dart-define=FIREBASE_PROJECT_ID=... \
///   --dart-define=FIREBASE_STORAGE_BUCKET=... \
///   --dart-define=FIREBASE_IOS_BUNDLE_ID=... 
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'please add web Firebase configuration separately.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'please add macOS Firebase configuration separately.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'please add Windows Firebase configuration separately.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: _androidApiKey,
    appId: _androidAppId,
    messagingSenderId: _messagingSenderId,
    projectId: _projectId,
    storageBucket: _storageBucket,
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: _iosApiKey,
    appId: _iosAppId,
    messagingSenderId: _messagingSenderId,
    projectId: _projectId,
    storageBucket: _storageBucket,
    iosBundleId: _iosBundleId,
  );
}
