# Generated by Django 4.2.30 on 2026-05-09 08:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChecklistTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('schema', models.JSONField(help_text='JSON schema definition for the checklist')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'checklist_templates',
            },
        ),
        migrations.CreateModel(
            name='ChecklistResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField(default=dict)),
                ('synced_at', models.DateTimeField(blank=True, null=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('is_draft', models.BooleanField(default=True)),
                ('last_saved_draft', models.DateTimeField(blank=True, null=True)),
                ('job', models.OneToOneField(help_text='The job this checklist belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='checklist_response', to='jobs.job')),
            ],
            options={
                'db_table': 'checklist_responses',
                'indexes': [models.Index(fields=['job', 'synced_at'], name='checklist_r_job_id_986f7a_idx'), models.Index(fields=['is_draft', 'last_modified'], name='checklist_r_is_draf_7e4fb0_idx')],
            },
        ),
    ]
