# Generated by Django 4.2.30 on 2026-05-09 08:01

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_id', models.CharField(db_index=True, help_text='Human-readable job identifier (e.g., JOB-2025-001)', max_length=50, unique=True)),
                ('customer_name', models.CharField(max_length=255)),
                ('customer_phone', models.CharField(max_length=20)),
                ('customer_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('customer_address', models.TextField()),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9, validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)])),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)])),
                ('description', models.TextField()),
                ('notes', models.TextField(blank=True, help_text='Internal notes for technician')),
                ('scheduled_start', models.DateTimeField(db_index=True)),
                ('scheduled_end', models.DateTimeField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('overdue', 'Overdue')], db_index=True, default='pending', max_length=20)),
                ('actual_start', models.DateTimeField(blank=True, null=True)),
                ('actual_completion', models.DateTimeField(blank=True, null=True)),
                ('checklist_schema', models.JSONField(default=dict, help_text='JSON schema defining the checklist fields for this job type')),
                ('version', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'jobs',
                'ordering': ['scheduled_start', 'job_id'],
                'indexes': [models.Index(fields=['assigned_to', 'status', 'scheduled_start'], name='jobs_assigne_4969dc_idx'), models.Index(fields=['id', 'version'], name='jobs_id_7bf285_idx'), models.Index(fields=['scheduled_start', 'scheduled_end'], name='jobs_schedul_435670_idx')],
            },
        ),
    ]
