# Generated by Django 4.2.30 on 2026-05-09 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Signature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signature_url', models.URLField(max_length=500)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('job', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='signature', to='jobs.job')),
            ],
            options={
                'db_table': 'signatures',
            },
        ),
    ]
